# Generated by Django 4.1.1 on 2022-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_alter_article_options_article_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
