# Generated by Django 4.1.1 on 2022-10-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='official_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
