# Generated by Django 4.1.1 on 2022-10-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_customuser_official_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='official_name',
        ),
    ]
