# Generated by Django 4.1.1 on 2022-10-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_remove_customuser_official_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
