# Generated by Django 4.1.1 on 2022-10-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0010_alter_additionaluserinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalUserInfo',
        ),
    ]
