# Generated by Django 4.1.1 on 2022-10-03 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0012_additionaluserinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalUserInfo',
            new_name='Profile',
        ),
    ]
