# Generated by Django 4.1.1 on 2022-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0013_rename_additionaluserinfo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='static/images/users/profile-images/'),
        ),
    ]
