# Generated by Django 4.1.1 on 2022-10-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0015_rename_date_of_the_birthday_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='static/images/users/profile-images/'),
        ),
    ]
